version: '3.4'

services:
  php81:
    build:
      context: ./docker/php81
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_event_calendar
      - ./docker/php81/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php81/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/php81/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
      - redis
  db:
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8081:81'
    volumes:
      - ./app:/var/www/symfony_event_calendar
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81
      - db
  redis:
    image: redis:7.0.4-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./docker/redis:/data