version: '3.4'

services:
  php81:
    container_name: php81
    build:
      context: ./php81
    ports:
      - '9000:9000'
    volumes:
      - ../app:/var/www/app
      - ./php81/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
      - redis
  db:
    container_name: db
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81
      - db
  redis:
    container_name: redis
    image: redis:7.0.4-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./redis:/data